### ISSUE TITLE
数据库链接 失败

### ISSUE THREAD

**Issue by wudi0431** [JDFED/pubfree#3]
<img width="1060" alt="image" src="https://github.com/JDFED/FEPubfree/assets/6140336/472617c5-2515-4eef-ac84-7a0b0fc4d417">
提升数据库链接失败

我本地 mysql 是可以的 正常链接的

<img width="912" alt="image" src="https://github.com/JDFED/FEPubfree/assets/6140336/d0d87ce5-9f3c-49a2-a6ff-513a6396267d">

**Comment by wudi0431** [comment]
> @midwayjs-examples/applicaiton-express@1.0.0 dev /Users/tianxia/Downloads/FEPubfree/packages/server-api
> cross-env NODE_ENV=local midway-bin dev --ts

⠧ Midway Starting 2023-07-26 12:28:32,986 INFO 25004 Configuration onReady
2023-07-26 12:28:32,988 INFO 25004 {
  orm: {
    host: '127.0.0.1',
    port: 3306,
    database: 'pubfree_open',
    username: 'root',
    password: '12345678'
  }
}
2023-07-26 12:28:32,989 INFO 25004 {
  host: '127.0.0.1',
  port: 3306,
  database: 'pubfree_open',
  username: 'root',
  password: '12345678'
}
⠏ Midway Starting
[ Midway ] start error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/typeorm@0.2.31/src/driver/mysql/MysqlDriver.ts:894:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/typeorm@0.2.31/src/driver/mysql/MysqlDriver.ts:891:16)
    at MysqlDriver.<anonymous> (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/typeorm@0.2.31/src/driver/mysql/MysqlDriver.ts:344:36)
    at step (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/tianxia/Downloads/FEPubfree/node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.js:122:57) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
}
